In [4]:
# concat - concatenating dataframes

import pandas as pd

df1 = pd.read_csv('first.csv')
df2 = pd.read_csv('second.csv')

#print(df1)

#print(df2)

df3 = pd.concat([df1,df2])

df3.reset_index() # reset the index from 0 to number of rows

print(df3)

    id   first_name   last_name                   company_name  \
0    1      Aleshia  Tomkiewicz        Alan D Rosenburg Cpa Pc
1    2         Evan   Zigomalas             Cap Gemini America
2    3       France     Andrade            Elliott, John W Esq
3    4      Ulysses   Mcwalters                 Mcmahan, Ben L
4    5       Tyisha      Veness                 Champagne Room
5    6         Eric       Rampy        Thompson, Michael C Esq
6    7         Marg    Grasmick  Wrangle Hill Auto Auct & Slvg
7    8      Laquita       Hisaw          In Communications Inc
8    9         Lura    Manzella                Bizerba Usa Inc
9   10       Yuette      Klapec                      Max Video
0   11     Fernanda      Writer           K & R Associates Inc
1   12  Charlesetta         Erm               Cain, John M Esq
2   13     Corrinne       Jaret              Sound Vision Corp
3   14       Niesha       Bruch         Rowley/hansell Petetin
4   15       Rueben   Gastellum  Industrial Engineering Assocs
5   16      Michell   Throssell            Weiss Spirt & Guyer
6   17        Edgar       Kanne          Crowan, Kenneth W Esq
7   18       Dewitt       Julio           Rittenhouse Motor Co
8   19     Charisse    Spinello           Modern Plastics Corp
9   20          Mee    Lapinski       Galloway Electric Co Inc
10  21        Peter   Gutierres     Niagara Custombuilt Mfg Co

                 address                            city  \
0           14 Taylor St               St. Stephens Ward
1            5 Binney St                      Abbey Ward
2           8 Moor Place  East Southbourne and Tuckton W
3          505 Exeter Rd              Hawerby cum Beesby
4      5396 Forth Street      Greets Green and Lyng Ward
5           9472 Lind St                      Desborough
6       7457 Cowl St #70                    Bargate Ward
7   20 Gloucester Pl #96                    Chirton Ward
8       929 Augustine St                Staple Hill Ward
9   45 Bradfield St #166                         Parwich
0     620 Northampton St                      Wilmington
1            5 Hygeia St            Loundsley Green Ward
2         2150 Morley St                        Dee Ward
3           24 Bolton St  Broxburn, Uphall and Winchburg
4           4 Forrest St               Weston-Super-Mare
5             89 Noon St                       Carbrooke
6          99 Guthrie St                      New Milton
7          7 Richmond St                         Parkham
8       9165 Primrose St                    Darnall Ward
9          9 Pengwern St                         Marldon
10       4410 Tarlton St             Prestatyn Community

                   county    postal        phone1        phone2  \
0                    Kent   CT2 7PP  01835-703597  01944-369967
1         Buckinghamshire  HP11 2AX  01937-864715  01714-737668
2             Bournemouth   BH6 3BE  01347-368222  01935-821636
3            Lincolnshire  DN36 5RP  01912-771311  01302-601380
4           West Midlands   B70 9DT  01547-429341  01290-367248
5        Northamptonshire  NN14 2GH  01969-886290  01545-817375
6             Southampton  SO14 3TY  01865-582516  01362-620532
7             Tyne & Wear  NE29 7AD  01746-394243  01590-982428
8   South Gloucestershire  BS16 4LL  01907-538509  01340-713951
9              Derbyshire   DE6 1QN  01903-649460  01933-512513
0                    Kent   DA2 7PP  01630-202053  01687-879391
1              Derbyshire   S40 4LY  01276-816806  01517-624517
2   Dumfries and Galloway   DG8 7DE  01625-932209  01642-322954
3            West Lothian  EH52 5TL  01874-856950  01342-793603
4          North Somerset  BS23 3HG  01976-755279  01956-535511
5                 Norfolk  IP25 6JQ  01967-580851  01672-496478
6               Hampshire  BH25 5DF  01326-532337  01666-638176
7                   Devon  EX39 5DJ  01253-528327  01241-964675
8        Yorkshire, South    S4 7WN  01719-831436  01207-428520
9                   Devon   TQ3 1SA  01578-287816  01939-815208
10           Denbighshire  LL19 9EG  01842-767201  01859-648598

                               email  \
0            atomkiewicz@hotmail.com
1           evan.zigomalas@gmail.com
2         france.andrade@hotmail.com
3                ulysses@hotmail.com
4          tyisha.veness@hotmail.com
5                 erampy@rampy.co.uk
6                   marg@hotmail.com
7                  laquita@yahoo.com
8                   lura@hotmail.com
9         yuette.klapec@klapec.co.uk
0              fernanda@writer.co.uk
1          charlesetta_erm@gmail.com
2           corrinne_jaret@gmail.com
3             niesha.bruch@yahoo.com
4   rueben_gastellum@gastellum.co.uk
5         mthrossell@throssell.co.uk
6              edgar.kanne@yahoo.com
7           dewitt.julio@hotmail.com
8   charisse_spinello@spinello.co.uk
9             mee.lapinski@yahoo.com
10         peter_gutierres@yahoo.com

                                             web    in  out
0           http://www.alandrosenburgcpapc.co.uk   9:3  NaN
1              http://www.capgeminiamerica.co.uk  9:13  NaN
2               http://www.elliottjohnwesq.co.uk  9:46  NaN
3                   http://www.mcmahanbenl.co.uk   9:4  NaN
4                 http://www.champagneroom.co.uk   8:1  NaN
5           http://www.thompsonmichaelcesq.co.uk  8:59  NaN
6       http://www.wranglehillautoauctslvg.co.uk  8:28  NaN
7           http://www.incommunicationsinc.co.uk  8:30  NaN
8                 http://www.bizerbausainc.co.uk  9:12  NaN
9                      http://www.maxvideo.co.uk  9:17  NaN
0               http://www.krassociatesinc.co.uk  8:18  NaN
1                  http://www.cainjohnmesq.co.uk  8:50  NaN
2               http://www.soundvisioncorp.co.uk  9:55  NaN
3          http://www.rowleyhansellpetetin.co.uk  9:37  NaN
4   http://www.industrialengineeringassocs.co.uk  8:38  NaN
5               http://www.weissspirtguyer.co.uk  8:49  NaN
6             http://www.crowankennethwesq.co.uk  9:22  NaN
7            http://www.rittenhousemotorco.co.uk  9:48  NaN
8            http://www.modernplasticscorp.co.uk  8:58  NaN
9         http://www.gallowayelectriccoinc.co.uk  8:30  NaN
10      http://www.niagaracustombuiltmfgco.co.uk   8:5  NaN